# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/stockDataPlots',
                'doc_host': 'https://kaiguender.github.io',
                'git_url': 'https://github.com/kaiguender/stockDataPlots',
                'lib_path': 'stockDataPlots'},
  'syms': {'stockDataPlots.core': {'stockDataPlots.core.foo': ('core.html#foo', 'stockDataPlots/core.py')}}}